### ISSUE TITLE
Middleware chaining restricted access.

### ISSUE THREAD

**Issue by dragfire** [TobiEiss/goMiddlewareChain#1]
In Express
`app.use("/admin", auth.checkAdmin, dashboard)`
if `auth.checkIn` is failed, then it won't pass to the next function.

Will it be posible to do this with `goMiddlewareChain`?

**Comment by TobiEiss** [comment]
Currently its not possible.
But its a nice task for weekend. ;-)

Stay tuned.

**Comment by dragfire** [comment]
Okay looking forward to it 👍

**Comment by TobiEiss** [comment]
Okay. It's done. Check out the readme.

**Comment by dragfire** [comment]
Thanks well done.
